on: [push]

jobs:
  merge_conflicts:
    runs-on: ubuntu-latest
    name: Check if any other branch is conflicting with ours
    steps:
    - uses: actions/checkout@v1
    - name: Alert on merge conflicts
      id: merge_conflicts
      uses: adamkleingit/merge-conflict-alert@master
      continue-on-error: true
    # Use the output from the `hello` step
    - name: Get the merge conflicts
      if: steps.merge_conflicts.outputs.conflicts
      run: echo "${{ steps.merge_conflicts.outputs.conflicts }}"
