on: [push]

jobs:
  merge_conflicts:
    runs-on: ubuntu-latest
    name: Check if any other branch is conflicting with ours
    steps:
    - uses: actions/checkout@v1
    - name: Alert on merge conflicts
      id: merge_conflicts
      uses: adamkleingit/merge-conflict-alert@master
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
    # Use the output from the `hello` step
    - name: Get the merge conflicts
      run: echo "The time was ${{ steps.merge_conflicts.outputs.conflicts }}"
