on: [push]

jobs:
  merge_conflicts:
    runs-on: ubuntu-latest
    name: Check if any other branch is conflicting with ours
    steps:
    - name: Alert on merge conflicts
      id: merge_conflicts
      uses: adamkleingit/merge-conflict-alert@v0.5
      with:
        who-to-greet: 'Mona the Octocat2'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.merge_conflicts.outputs.time }}"
